# Generated by Django 3.1.7 on 2021-05-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=10, help_text='<span class="text-danger" style="font-size: 0.9rem">Cantidad a pagar por su pedido</span>', max_digits=50, verbose_name='Total'),
        ),
    ]
