# Generated by Django 3.1.7 on 2021-03-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='video',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='hobbies', verbose_name='Video'),
        ),
    ]
